// Code generated by protoc-gen-go-grpc_server. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc_server v1.3.0
// - protoc             v3.21.12
// source: game.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc_server package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Game_GameList_FullMethodName   = "/Game/GameList"
	Game_GameDetail_FullMethodName = "/Game/GameDetail"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameClient interface {
	GameList(ctx context.Context, in *GameListFilterRequest, opts ...grpc.CallOption) (*GameListResponse, error)
	GameDetail(ctx context.Context, in *GameDetailRequest, opts ...grpc.CallOption) (*GameDetailInfoResp, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) GameList(ctx context.Context, in *GameListFilterRequest, opts ...grpc.CallOption) (*GameListResponse, error) {
	out := new(GameListResponse)
	err := c.cc.Invoke(ctx, Game_GameList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GameDetail(ctx context.Context, in *GameDetailRequest, opts ...grpc.CallOption) (*GameDetailInfoResp, error) {
	out := new(GameDetailInfoResp)
	err := c.cc.Invoke(ctx, Game_GameDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility
type GameServer interface {
	GameList(context.Context, *GameListFilterRequest) (*GameListResponse, error)
	GameDetail(context.Context, *GameDetailRequest) (*GameDetailInfoResp, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (UnimplementedGameServer) GameList(context.Context, *GameListFilterRequest) (*GameListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameList not implemented")
}
func (UnimplementedGameServer) GameDetail(context.Context, *GameDetailRequest) (*GameDetailInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameDetail not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_GameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameListFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GameList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GameList(ctx, req.(*GameListFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GameDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GameDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GameDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GameDetail(ctx, req.(*GameDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc_server.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GameList",
			Handler:    _Game_GameList_Handler,
		},
		{
			MethodName: "GameDetail",
			Handler:    _Game_GameDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
